### ISSUE TITLE
Migrate classname

### ISSUE THREAD

**Issue by ridv** [aurora-scheduler/scheduler#59]
Move from `org.apache.aurora` to `io.github.aurora-scheduler`

This may be easy or it may not be worth the time.

**Comment by zorro786** [comment]
This will break backward compatibility right? Will need to go in as 1.0.0?

**Comment by ridv** [comment]
Most likely yes. I don't foresee it breaking compatibility with other components since they communicate via thrift.

**Comment by ridv** [comment]
Closing this as won't fix. Not worth the effort.
